package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTeacher<M extends BaseTeacher<M>> extends Model<M> implements IBean {

	public M setTeacherId(java.lang.Integer teacherId) {
		set("teacher_id", teacherId);
		return (M)this;
	}

	public java.lang.Integer getTeacherId() {
		return get("teacher_id");
	}

	public M setTeacherName(java.lang.String teacherName) {
		set("teacher_name", teacherName);
		return (M)this;
	}

	public java.lang.String getTeacherName() {
		return get("teacher_name");
	}

	public M setTeacherMotto(java.lang.String teacherMotto) {
		set("teacher_motto", teacherMotto);
		return (M)this;
	}

	public java.lang.String getTeacherMotto() {
		return get("teacher_motto");
	}

	public M setTeacherTel(java.lang.String teacherTel) {
		set("teacher_tel", teacherTel);
		return (M)this;
	}

	public java.lang.String getTeacherTel() {
		return get("teacher_tel");
	}

	public M setTeacherEmail(java.lang.String teacherEmail) {
		set("teacher_email", teacherEmail);
		return (M)this;
	}

	public java.lang.String getTeacherEmail() {
		return get("teacher_email");
	}

	public M setTeacherContent(java.lang.String teacherContent) {
		set("teacher_content", teacherContent);
		return (M)this;
	}

	public java.lang.String getTeacherContent() {
		return get("teacher_content");
	}

}
