package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseActivity<M extends BaseActivity<M>> extends Model<M> implements IBean {

	public M setActivityId(java.lang.Integer activityId) {
		set("activity_id", activityId);
		return (M)this;
	}

	public java.lang.Integer getActivityId() {
		return get("activity_id");
	}

	public M setActivityContent(java.lang.String activityContent) {
		set("activity_content", activityContent);
		return (M)this;
	}

	public java.lang.String getActivityContent() {
		return get("activity_content");
	}

}
