package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePostbar<M extends BasePostbar<M>> extends Model<M> implements IBean {

	public M setPostbarId(java.lang.Integer postbarId) {
		set("postbar_id", postbarId);
		return (M)this;
	}

	public java.lang.Integer getPostbarId() {
		return get("postbar_id");
	}

	public M setPostbarTitle(java.lang.String postbarTitle) {
		set("postbar_title", postbarTitle);
		return (M)this;
	}

	public java.lang.String getPostbarTitle() {
		return get("postbar_title");
	}

	public M setPostbarContent(java.lang.String postbarContent) {
		set("postbar_content", postbarContent);
		return (M)this;
	}

	public java.lang.String getPostbarContent() {
		return get("postbar_content");
	}

}
