package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseQueAnswer<M extends BaseQueAnswer<M>> extends Model<M> implements IBean {

	public M setQueId(java.lang.Integer queId) {
		set("que_id", queId);
		return (M)this;
	}

	public java.lang.Integer getQueId() {
		return get("que_id");
	}

	public M set1(java.lang.String 1) {
		set("1", 1);
		return (M)this;
	}

	public java.lang.String get1() {
		return get("1");
	}

	public M set2(java.lang.String 2) {
		set("2", 2);
		return (M)this;
	}

	public java.lang.String get2() {
		return get("2");
	}

	public M set3(java.lang.String 3) {
		set("3", 3);
		return (M)this;
	}

	public java.lang.String get3() {
		return get("3");
	}

	public M set4(java.lang.String 4) {
		set("4", 4);
		return (M)this;
	}

	public java.lang.String get4() {
		return get("4");
	}

}
