package common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseArticle<M extends BaseArticle<M>> extends Model<M> implements IBean {

	public M setArticleId(java.lang.Integer articleId) {
		set("article_id", articleId);
		return (M)this;
	}

	public java.lang.Integer getArticleId() {
		return get("article_id");
	}

	public M setArticleTitle(java.lang.String articleTitle) {
		set("article_title", articleTitle);
		return (M)this;
	}

	public java.lang.String getArticleTitle() {
		return get("article_title");
	}

	public M setUserAccount(java.lang.String userAccount) {
		set("user_account", userAccount);
		return (M)this;
	}

	public java.lang.String getUserAccount() {
		return get("user_account");
	}

	public M setArticleContent(java.lang.String articleContent) {
		set("article_content", articleContent);
		return (M)this;
	}

	public java.lang.String getArticleContent() {
		return get("article_content");
	}

	public M setPostTime(java.lang.String postTime) {
		set("post_time", postTime);
		return (M)this;
	}

	public java.lang.String getPostTime() {
		return get("post_time");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

}
