package common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseQuestion<M extends BaseQuestion<M>> extends Model<M> implements IBean {

	public M setQuestionId(Integer questionId) {
		set("question_id", questionId);
		return (M)this;
	}

	public Integer getQuestionId() {
		return get("question_id");
	}

	public M setQuestionContent(String questionContent) {
		set("question_content", questionContent);
		return (M)this;
	}

	public String getQuestionContent() {
		return get("question_content");
	}

	public M setQuestionTrueAnswer(Integer questionTrueAnswer) {
		set("question_true_answer", questionTrueAnswer);
		return (M)this;
	}

	public Integer getQuestionTrueAnswer() {
		return get("question_true_answer");
	}

}
