package common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({ "serial", "unchecked" })
public abstract class BaseActivity<M extends BaseActivity<M>> extends Model<M> implements IBean {

	public M setActivityId(java.lang.Integer activityId) {
		set("activity_id", activityId);
		return (M) this;
	}

	public java.lang.Integer getActivityId() {
		return get("activity_id");
	}

	public M setActivityTheme(java.lang.String activityTheme) {
		set("activity_theme", activityTheme);
		return (M) this;
	}

	public java.lang.String getActivityTheme() {
		return get("activity_theme");
	}

	public M setActivityContent(java.lang.String activityContent) {
		set("activity_content", activityContent);
		return (M) this;
	}

	public java.lang.String getActivityContent() {
		return get("activity_content");
	}

	public M setActivityPlace(java.lang.String activityPlace) {
		set("activity_place", activityPlace);
		return (M) this;
	}

	public java.lang.String getActivityPlace() {
		return get("activity_place");
	}

	public M setActivityTime(java.lang.String activityTime) {
		set("activity_time", activityTime);
		return (M) this;
	}

	public java.lang.String getActivityTime() {
		return get("activity_time");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M) this;
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public M setActivityCompere(java.lang.String activityCompere) {
		set("activity_compere", activityCompere);
		return (M) this;
	}

	public java.lang.String getActivityCompere() {
		return get("activity_compere");
	}

}
