package common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAppointment<M extends BaseAppointment<M>> extends Model<M> implements IBean {

	public M setAppointmentId(java.lang.Integer appointmentId) {
		set("appointment_id", appointmentId);
		return (M)this;
	}

	public java.lang.Integer getAppointmentId() {
		return get("appointment_id");
	}

	public M setActivityId(java.lang.Integer activityId) {
		set("activity_id", activityId);
		return (M)this;
	}

	public java.lang.Integer getActivityId() {
		return get("activity_id");
	}

	public M setUserAccount(java.lang.String userAccount) {
		set("user_account", userAccount);
		return (M)this;
	}

	public java.lang.String getUserAccount() {
		return get("user_account");
	}

	public M setDescription(java.lang.String description) {
		set("description", description);
		return (M)this;
	}

	public java.lang.String getDescription() {
		return get("description");
	}

	public M setUserTel(java.lang.String userTel) {
		set("user_tel", userTel);
		return (M)this;
	}

	public java.lang.String getUserTel() {
		return get("user_tel");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public M setTime(java.lang.String time) {
		set("time", time);
		return (M)this;
	}

	public java.lang.String getTime() {
		return get("time");
	}

}
