package common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseQuestion<M extends BaseQuestion<M>> extends Model<M> implements IBean {

	public M setQueId(java.lang.Integer queId) {
		set("que_id", queId);
		return (M)this;
	}

	public java.lang.Integer getQueId() {
		return get("que_id");
	}

	public M setQueContent(java.lang.String queContent) {
		set("que_content", queContent);
		return (M)this;
	}

	public java.lang.String getQueContent() {
		return get("que_content");
	}

	public M setQueTrueAnswer(java.lang.Integer queTrueAnswer) {
		set("que_true_answer", queTrueAnswer);
		return (M)this;
	}

	public java.lang.Integer getQueTrueAnswer() {
		return get("que_true_answer");
	}

}
