package common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUserInformation<M extends BaseUserInformation<M>> extends Model<M> implements IBean {

	public M setUserId(Integer userId) {
		set("user_id", userId);
		return (M)this;
	}

	public Integer getUserId() {
		return get("user_id");
	}

	public M setUserAccount(String userAccount) {
		set("user_account", userAccount);
		return (M)this;
	}

	public String getUserAccount() {
		return get("user_account");
	}

	public M setUserPassword(String userPassword) {
		set("user_password", userPassword);
		return (M)this;
	}

	public String getUserPassword() {
		return get("user_password");
	}

	public M setUserPhone(String userPhone) {
		set("user_phone", userPhone);
		return (M)this;
	}

	public String getUserPhone() {
		return get("user_phone");
	}

	public M setUserSex(Integer userSex) {
		set("user_sex", userSex);
		return (M)this;
	}

	public Integer getUserSex() {
		return get("user_sex");
	}

	public M setUserDescription(String userDescription) {
		set("user_description", userDescription);
		return (M)this;
	}

	public String getUserDescription() {
		return get("user_description");
	}

	public M setUserTruename(String userTruename) {
		set("user_truename", userTruename);
		return (M)this;
	}

	public String getUserTruename() {
		return get("user_truename");
	}

}
