package common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTeacher<M extends BaseTeacher<M>> extends Model<M> implements IBean {

	public M setTecId(java.lang.Integer tecId) {
		set("tec_id", tecId);
		return (M)this;
	}

	public java.lang.Integer getTecId() {
		return get("tec_id");
	}

	public M setTecName(java.lang.String tecName) {
		set("tec_name", tecName);
		return (M)this;
	}

	public java.lang.String getTecName() {
		return get("tec_name");
	}

	public M setTecDescription(java.lang.String tecDescription) {
		set("tec_description", tecDescription);
		return (M)this;
	}

	public java.lang.String getTecDescription() {
		return get("tec_description");
	}

	public M setTecPhone(java.lang.String tecPhone) {
		set("tec_phone", tecPhone);
		return (M)this;
	}

	public java.lang.String getTecPhone() {
		return get("tec_phone");
	}

}
