package common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseQuery<M extends BaseQuery<M>> extends Model<M> implements IBean {

	public M setQueId(java.lang.Integer queId) {
		set("que_id", queId);
		return (M)this;
	}

	public java.lang.Integer getQueId() {
		return get("que_id");
	}

	public M setQueContent(java.lang.String queContent) {
		set("que_content", queContent);
		return (M)this;
	}

	public java.lang.String getQueContent() {
		return get("que_content");
	}

	public M setQueTrueanswer(java.lang.Integer queTrueanswer) {
		set("que_trueanswer", queTrueanswer);
		return (M)this;
	}

	public java.lang.Integer getQueTrueanswer() {
		return get("que_trueanswer");
	}

}
