package common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePostbarComment<M extends BasePostbarComment<M>> extends Model<M> implements IBean {

	public M setPostId(java.lang.Integer postId) {
		set("post_id", postId);
		return (M)this;
	}

	public java.lang.Integer getPostId() {
		return get("post_id");
	}

	public M setUserId(java.lang.String userId) {
		set("user_id", userId);
		return (M)this;
	}

	public java.lang.String getUserId() {
		return get("user_id");
	}

	public M setCommentContent(java.lang.String commentContent) {
		set("comment_content", commentContent);
		return (M)this;
	}

	public java.lang.String getCommentContent() {
		return get("comment_content");
	}

	public M setCommentTime(java.util.Date commentTime) {
		set("comment_time", commentTime);
		return (M)this;
	}

	public java.util.Date getCommentTime() {
		return get("comment_time");
	}

}
