package common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseQueAnswer<M extends BaseQueAnswer<M>> extends Model<M> implements IBean {

	public M setQueId(java.lang.Integer queId) {
		set("que_id", queId);
		return (M)this;
	}

	public java.lang.Integer getQueId() {
		return get("que_id");
	}

	public M setOne(java.lang.String one) {
		set("one", one);
		return (M)this;
	}

	public java.lang.String getOne() {
		return get("one");
	}

	public M setTwo(java.lang.String two) {
		set("two", two);
		return (M)this;
	}

	public java.lang.String getTwo() {
		return get("two");
	}

	public M setThree(java.lang.String three) {
		set("three", three);
		return (M)this;
	}

	public java.lang.String getThree() {
		return get("three");
	}

	public M setFour(java.lang.String four) {
		set("four", four);
		return (M)this;
	}

	public java.lang.String getFour() {
		return get("four");
	}

}
