package common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseArticle<M extends BaseArticle<M>> extends Model<M> implements IBean {

	public M setArtId(java.lang.Integer artId) {
		set("art_id", artId);
		return (M)this;
	}

	public java.lang.Integer getArtId() {
		return get("art_id");
	}

	public M setArtName(java.lang.String artName) {
		set("art_name", artName);
		return (M)this;
	}

	public java.lang.String getArtName() {
		return get("art_name");
	}

	public M setUserId(java.lang.String userId) {
		set("user_id", userId);
		return (M)this;
	}

	public java.lang.String getUserId() {
		return get("user_id");
	}

	public M setArtContent(java.lang.String artContent) {
		set("art_content", artContent);
		return (M)this;
	}

	public java.lang.String getArtContent() {
		return get("art_content");
	}

	public M setPostTime(java.lang.String postTime) {
		set("post_time", postTime);
		return (M)this;
	}

	public java.lang.String getPostTime() {
		return get("post_time");
	}

}
