package common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseQueAnswer<M extends BaseQueAnswer<M>> extends Model<M> implements IBean {

	public M setQueId(java.lang.Integer queId) {
		set("que_id", queId);
		return (M)this;
	}

	public java.lang.Integer getQueId() {
		return get("que_id");
	}

	public M setAnswerOne(java.lang.String answerOne) {
		set("answer_one", answerOne);
		return (M)this;
	}

	public java.lang.String getAnswerOne() {
		return get("answer_one");
	}

	public M setAnswerTwo(java.lang.String answerTwo) {
		set("answer_two", answerTwo);
		return (M)this;
	}

	public java.lang.String getAnswerTwo() {
		return get("answer_two");
	}

	public M setAnswerThree(java.lang.String answerThree) {
		set("answer_three", answerThree);
		return (M)this;
	}

	public java.lang.String getAnswerThree() {
		return get("answer_three");
	}

	public M setAnswerFour(java.lang.String answerFour) {
		set("answer_four", answerFour);
		return (M)this;
	}

	public java.lang.String getAnswerFour() {
		return get("answer_four");
	}

}
