package common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseComment<M extends BaseComment<M>> extends Model<M> implements IBean {

	public M setCommentId(Integer commentId) {
		set("comment_id", commentId);
		return (M)this;
	}

	public Integer getCommentId() {
		return get("comment_id");
	}

	public M setPostId(Integer postId) {
		set("post_id", postId);
		return (M)this;
	}

	public Integer getPostId() {
		return get("post_id");
	}

	public M setUserAccount(String userAccount) {
		set("user_account", userAccount);
		return (M)this;
	}

	public String getUserAccount() {
		return get("user_account");
	}

	public M setCommentContent(String commentContent) {
		set("comment_content", commentContent);
		return (M)this;
	}

	public String getCommentContent() {
		return get("comment_content");
	}

	public M setCommentTime(Integer commentTime) {
		set("comment_time", commentTime);
		return (M)this;
	}

	public Integer getCommentTime() {
		return get("comment_time");
	}

	public M setStatus(Integer status) {
		set("status", status);
		return (M)this;
	}

	public Integer getStatus() {
		return get("status");
	}

}
