package common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTeacher<M extends BaseTeacher<M>> extends Model<M> implements IBean {

	public M setTeacherId(Integer teacherId) {
		set("teacher_id", teacherId);
		return (M)this;
	}

	public Integer getTeacherId() {
		return get("teacher_id");
	}

	public M setTeacherName(String teacherName) {
		set("teacher_name", teacherName);
		return (M)this;
	}

	public String getTeacherName() {
		return get("teacher_name");
	}

	public M setTeacherMotto(String teacherMotto) {
		set("teacher_motto", teacherMotto);
		return (M)this;
	}

	public String getTeacherMotto() {
		return get("teacher_motto");
	}

	public M setTeacherTel(String teacherTel) {
		set("teacher_tel", teacherTel);
		return (M)this;
	}

	public String getTeacherTel() {
		return get("teacher_tel");
	}

	public M setTeacherEmail(String teacherEmail) {
		set("teacher_email", teacherEmail);
		return (M)this;
	}

	public String getTeacherEmail() {
		return get("teacher_email");
	}

	public M setTeacherDesc(String teacherDesc) {
		set("teacher_desc", teacherDesc);
		return (M)this;
	}

	public String getTeacherDesc() {
		return get("teacher_desc");
	}

}
