package common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePost<M extends BasePost<M>> extends Model<M> implements IBean {

	public M setPostId(Integer postId) {
		set("post_id", postId);
		return (M)this;
	}

	public Integer getPostId() {
		return get("post_id");
	}

	public M setPostTitle(String postTitle) {
		set("post_title", postTitle);
		return (M)this;
	}

	public String getPostTitle() {
		return get("post_title");
	}

	public M setPostContent(String postContent) {
		set("post_content", postContent);
		return (M)this;
	}

	public String getPostContent() {
		return get("post_content");
	}

	public M setPostTime(Integer postTime) {
		set("post_time", postTime);
		return (M)this;
	}

	public Integer getPostTime() {
		return get("post_time");
	}

	public M setUserAccount(String userAccount) {
		set("user_account", userAccount);
		return (M)this;
	}

	public String getUserAccount() {
		return get("user_account");
	}

}
