package common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseExamResult<M extends BaseExamResult<M>> extends Model<M> implements IBean {

	public M setUserAccount(String userAccount) {
		set("user_account", userAccount);
		return (M)this;
	}

	public String getUserAccount() {
		return get("user_account");
	}

	public M setQutihua(String qutihua) {
		set("qutihua", qutihua);
		return (M)this;
	}

	public String getQutihua() {
		return get("qutihua");
	}

	public M setQiangpo(String qiangpo) {
		set("qiangpo", qiangpo);
		return (M)this;
	}

	public String getQiangpo() {
		return get("qiangpo");
	}

	public M setJiaolv(String jiaolv) {
		set("jiaolv", jiaolv);
		return (M)this;
	}

	public String getJiaolv() {
		return get("jiaolv");
	}

	public M setDidui(String didui) {
		set("didui", didui);
		return (M)this;
	}

	public String getDidui() {
		return get("didui");
	}

	public M setKongbu(String kongbu) {
		set("kongbu", kongbu);
		return (M)this;
	}

	public String getKongbu() {
		return get("kongbu");
	}

	public M setPianzhi(String pianzhi) {
		set("pianzhi", pianzhi);
		return (M)this;
	}

	public String getPianzhi() {
		return get("pianzhi");
	}

	public M setJingshenbing(String jingshenbing) {
		set("jingshenbing", jingshenbing);
		return (M)this;
	}

	public String getJingshenbing() {
		return get("jingshenbing");
	}

	public M setShuimian(String shuimian) {
		set("shuimian", shuimian);
		return (M)this;
	}

	public String getShuimian() {
		return get("shuimian");
	}

	public M setDate(String date) {
		set("date", date);
		return (M)this;
	}

	public String getDate() {
		return get("date");
	}

	public M setExamId(Integer examId) {
		set("exam_id", examId);
		return (M)this;
	}

	public Integer getExamId() {
		return get("exam_id");
	}

}
