package common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseComment<M extends BaseComment<M>> extends Model<M> implements IBean {

	public M setCommentId(java.lang.Integer commentId) {
		set("comment_id", commentId);
		return (M)this;
	}

	public java.lang.Integer getCommentId() {
		return get("comment_id");
	}

	public M setPostId(java.lang.Integer postId) {
		set("post_id", postId);
		return (M)this;
	}

	public java.lang.Integer getPostId() {
		return get("post_id");
	}

	public M setUserAccount(java.lang.String userAccount) {
		set("user_account", userAccount);
		return (M)this;
	}

	public java.lang.String getUserAccount() {
		return get("user_account");
	}

	public M setCommentContent(java.lang.String commentContent) {
		set("comment_content", commentContent);
		return (M)this;
	}

	public java.lang.String getCommentContent() {
		return get("comment_content");
	}

	public M setCommentTime(java.lang.Integer commentTime) {
		set("comment_time", commentTime);
		return (M)this;
	}

	public java.lang.Integer getCommentTime() {
		return get("comment_time");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public M setParentId(java.lang.Integer parentId) {
		set("parent_id", parentId);
		return (M)this;
	}

	public java.lang.Integer getParentId() {
		return get("parent_id");
	}

}
