package common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUserInformation<M extends BaseUserInformation<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setUserId(java.lang.String userId) {
		set("user_id", userId);
		return (M)this;
	}

	public java.lang.String getUserId() {
		return get("user_id");
	}

	public M setUserPassword(java.lang.String userPassword) {
		set("user_password", userPassword);
		return (M)this;
	}

	public java.lang.String getUserPassword() {
		return get("user_password");
	}

	public M setUserPhone(java.lang.String userPhone) {
		set("user_phone", userPhone);
		return (M)this;
	}

	public java.lang.String getUserPhone() {
		return get("user_phone");
	}

	public M setUserSex(java.lang.Integer userSex) {
		set("user_sex", userSex);
		return (M)this;
	}

	public java.lang.Integer getUserSex() {
		return get("user_sex");
	}

	public M setUserDescription(java.lang.String userDescription) {
		set("user_description", userDescription);
		return (M)this;
	}

	public java.lang.String getUserDescription() {
		return get("user_description");
	}

	public M setUserTruename(java.lang.String userTruename) {
		set("user_truename", userTruename);
		return (M)this;
	}

	public java.lang.String getUserTruename() {
		return get("user_truename");
	}

}
