package common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("activity", "activity_id", Activity.class);
		arp.addMapping("appointment", "appointment_id", Appointment.class);
		arp.addMapping("article", "article_id", Article.class);
		arp.addMapping("comment", "comment_id", Comment.class);
		arp.addMapping("post", "post_id", Post.class);
		arp.addMapping("que_answer", "que_id", QueAnswer.class);
		arp.addMapping("question", "question_id", Question.class);
		arp.addMapping("teacher", "teacher_id", Teacher.class);
		arp.addMapping("user_information", "user_id", UserInformation.class);
	}
}

