package common.model;

import common.model.base.BaseAppointment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Appointment extends BaseAppointment<Appointment> {
	public static final Appointment dao = new Appointment().dao();
}
