package common.model;



import java.util.List;

import com.jfinal.plugin.activerecord.Page;

import common.model.base.BaseArticle;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Article extends BaseArticle<Article> {
	
	public static final Article dao = new Article().dao();
	
	public Page<Article> paginate(int pageNumber, int pageSize) {
		return paginate(pageNumber, pageSize, "select art_id,art_name", "from article order by post_time desc");
	}
	
	public Article findArticleById(int artId){
		return dao.findById(artId);
	}
	
	public List<Article> findArticles(){
		String sql = "SELECT * FROM ARTICLE";
		return dao.find(sql);
	}
}
