package common.model;

import common.model.base.BaseExamResult;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ExamResult extends BaseExamResult<ExamResult> {
	public static final ExamResult dao = new ExamResult().dao();
}
