package common.model;

import common.model.base.BasePostbarComment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PostbarComment extends BasePostbarComment<PostbarComment> {
	public static final PostbarComment dao = new PostbarComment().dao();
}
