package common.model;

import java.util.List;

import common.model.base.BaseTeacher;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Teacher extends BaseTeacher<Teacher> {
	public static final Teacher dao = new Teacher().dao();
	
	public List<Teacher> findTeachers(){
		String sql = "SELECT * FROM TEACHER";
		return dao.find(sql);
	}
}
