package common.model;

import common.model.base.BaseUserAppointment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserAppointment extends BaseUserAppointment<UserAppointment> {
	public static final UserAppointment dao = new UserAppointment().dao();
}
