package common.model;

import common.model.base.BaseUserInformation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserInformation extends BaseUserInformation<UserInformation> {
	public static final UserInformation dao = new UserInformation().dao();
}
