package com.demo.common.model;

import com.demo.common.model.base.BasePostbar;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Postbar extends BasePostbar<Postbar> {
	public static final Postbar dao = new Postbar().dao();
}
