package com.demo.common.model;

import com.demo.common.model.base.BaseQueAnswer;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class QueAnswer extends BaseQueAnswer<QueAnswer> {
	public static final QueAnswer dao = new QueAnswer().dao();
}
