package com.demo.common.model;

import com.demo.common.model.base.BaseQuery;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Query extends BaseQuery<Query> {
	public static final Query dao = new Query().dao();
}
